bash:
  .bash_profile: ~/.bash_profile
  .bashrc: ~/.bashrc

git:
  .gitconfig_main:  ~/.gitconfig
  .gitconfig_dskwrite: ~/.gitconfig_dskwrite

mackup:
  .mackup.cfg: ~/.mackup.cfg

nushell:
  env.nu: ~/Library/Application Support/nushell/env.nu
  config.nu: ~/Library/Application Support/nushell/config.nu

powershell:
  profile.ps1: ~/.config/powershell/Microsoft.PowerShell_profile.ps1

zsh:
  .zprofile: ~/.zprofile
  .zshrc: ~/.zshrc
